### ISSUE TITLE
Docs type annotation example fails in parser, is probably incorrect

### ISSUE THREAD

**Issue by JoeUX** [amzn/ion-docs#123]
The [main Ion docs page](https://amzn.github.io/ion-docs/) features these examples for type annotations:
```
dollars::100.0
height::inches::72
lotto_numbers::[7, 9, 19, 40, 42, 44]
```

I was curious about the second one (height) because it has two colons before the annotation instead of the single colon in the parser example, so I pasted it into the parser (the built-in parser at the bottom of the Docs page):
```
Error:  unexpected character '58'
```
I assume the example is incorrect and the parser is right?

**Comment by zslayton** [comment]
In the example `height::inches::72`, `height` and `inches` are both annotations on the integer value `72`. Parsing this expression as a top-level value works okay:

![image](https://user-images.githubusercontent.com/611616/85226062-7314b700-b3a3-11ea-9a9a-c450487d4140.png)


> it has two colons before the annotation instead of the single colon in the parser example

I suspect what's happened here is that you've added `height::inches::72` inside of the pre-loaded example struct, like this:

![image](https://user-images.githubusercontent.com/611616/85226144-f33b1c80-b3a3-11ea-9f86-3ec82393045e.png)

This occurs because when the parser is inside a struct, it expects to find a field name before it encounters a value. Field names and values are separated by a single colon. You can tweak the broken example by adding `height` as a field name:

![image](https://user-images.githubusercontent.com/611616/85226207-617fdf00-b3a4-11ea-952a-629b35a2aecb.png)

Now `height::inches::72` is a struct field named `height` that happens to also have the annotation `height`.

**Comment by JoeUX** [comment]
Got it, thanks. It might be worth saying this in the docs, that inside structs you can't use type annotations without declaring a field name first, unless this is obvious to everyone.
