### ISSUE TITLE
spaces, numbers, and timestamps in sexp

### ISSUE THREAD

**Issue by 9il** [amzn/ion-docs#143]
Spec allows `(a+b)`. At the same time, python code fails for `(1+2)` and passes for `(1 + 2)` (with spaces).

If the spec allows `(1+2)`, then it should allow `2021-01`, which is a correct timestamp.

I am a bit confused about spaces. Where they are required and where they don't?

**Comment by zslayton** [comment]
> I am a bit confused about spaces. Where they are required and where they don't?

Unfortunately, the parsing rules get rather complicated inside of s-expressions. Here's an excerpt from [the `Symbols` section](https://amzn.github.io/ion-docs/docs/spec.html#symbol) of the Ion spec:

> Within S-expressions, the rules for unquoted symbols include another set of tokens: operators. An operator is an unquoted sequence of one or more of the following nineteen ASCII characters: ``!#%&*+-./;<=>?@^`|~`` Operators and identifiers can be juxtaposed without whitespace [...]

> Spec allows (a+b).

In this case, the parser considers `a` to be an identifier (an unquoted symbol), `+` to be an operator (because we're inside an s-expression), and `b` to be another identifier. As the spec notes, no spaces are required in this case.

> At the same time, python code fails for (1+2) and passes for (1 + 2) (with spaces).

The no-spaces exception above only applies to neighboring identifiers and operators, and so doesn't extend to integers. Per [the `Integers` section](https://amzn.github.io/ion-docs/docs/spec.html#int) of the spec:

> In the text notation, integer values must be followed by one of the fifteen numeric stop-characters: ``{}[](),\"\'\ \t\n\r\v\f``.

(It's hard to see in GitHub's rendered Markdown, but one of the stop-characters is a space.)

> If the spec allows (1+2), then it should allow 2021-01, which is a correct timestamp.

Very good eye! However, `2021-01` is not a valid timestamp for exactly this reason. From [the `Timestamps` section](https://amzn.github.io/ion-docs/docs/spec.html#timestamp) of the spec:

> In the text format, timestamps follow the W3C note on date and time formats, but they must end with the literal “T” if not at least whole-day precision.
> ...
> ```
> 2007                             // Not a timestamp, but an int
> 2007-01                          // ERROR: Must end with 'T' if not whole-day precision,
>                                  // this results as an invalid-numeric-stopper error
> ```

Hopefully that was helpful. Does that answer your question?

**Comment by 9il** [comment]
Thank you for the clear answer! I missed the spec details.
